apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Project-A-Kubernetes/Project_A_Prometheus-stacks.git
    path: stacks/kube-prometheus-stack
    targetRevision: main
    helm: 
      skipCrds: true 
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncOptions:
  - createNamespace=true 