apiVersion: argoproj.io/v1alpha1 
kind: Application 
metadata:
  name: kube-prometheus-stack 
  namespace: argocd 
spec:
  project: default 
  source:
  - repoURL: "https://prometheus-community.github.io/helm-charts" 
    chart: kube-prometheus-stack
    targetRevision: 82.2.1
    helm:
      valueFiles:
        - $values-repo/prometheus-stacks/stacks/value.yml

  - repoURL: "https://github.com/Project-A-Kubernetes/Project_A_Prometheus-stacks.git"
    targetRevision: main 
    ref: values-repo

  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitor 
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true 
