#configuring argocd 
apiVersion:  argoproj.io/v1alpha1  
kind: Application 
metadata:
  name: sc-argocd 
  namespace: argocd 
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true

spec:
  project: default 
  source:
    repoURL: "https://github.com/Project-A-Kubernetes/Project_A_Prometheus-stacks.git"
    targetRevision: main 
    path: tools/
  destination: 
    server: "https://kubernetes.default.svc"
    namespace: kube-system
  syncPolicy: 
    automated:
      prune: true 
      selfHeal: true 
  
