#configuring argocd 
apiVersion:  argoproj.io/v1alpha1  
kind: Application 
metadata:
  name: tool-cluster 
  namespace: argocd 

spec:
  project: default 
  source:
    repoURL: "https://github.com/Project-A-Kubernetes/Project_A_Prometheus-stacks.git"
    targetRevision: main 
    path: tools/
  destination: 
    server: "https://kubernetes.default.svc"
    namespace: kube-system
  syncPolicy: 
    automated:
      prune: true 
      selfHeal: true 
    syncOptions:
      - ServerSideApply=true 
  
